@startuml

title "sequence about sqsd stat"
hide footbox

actor User

participant StatServer
participant QueueTracker

User -> StatServer : /worker/pause
activate StatServer
StatServer -> QueueTracker : Pause()
activate QueueTracker
QueueTracker -> QueueTracker : JobWorking = false
StatServer <-- QueueTracker
deactivate QueueTracker
User <-- StatServer : response
deactivate StatServer

User -> StatServer : /worker/resume
activate StatServer
StatServer -> QueueTracker : Resume()
activate QueueTracker
QueueTracker -> QueueTracker : JobWorking = true
StatServer <-- QueueTracker
deactivate QueueTracker
User <-- StatServer : response
deactivate StatServer

User -> StatServer : /worker/current
activate StatServer
StatServer -> QueueTracker : CurrentSummary()
activate QueueTracker
StatServer <-- QueueTracker : *StatResponseCurrentSummary
deactivate QueueTracker
User <-- StatServer : response
deactivate StatServer

User -> StatServer : /worker/current/jobs
activate StatServer
StatServer -> QueueTracker : CurrentJobs()
activate QueueTracker
StatServer <-- QueueTracker : *StatResponseCurrentJobs
deactivate QueueTracker
User <-- StatServer : response
deactivate StatServer

User -> StatServer : /stats
activate StatServer
User <-- StatServer : response
deactivate StatServer


@enduml